# Generated by Django 3.1.4 on 2021-01-24 05:40

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('shopName', models.CharField(max_length=100)),
                ('typeOf', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=150)),
                ('image1', models.ImageField(upload_to=Main.models.user_directory_path2)),
                ('image2', models.ImageField(upload_to=Main.models.user_directory_path2)),
                ('image3', models.ImageField(upload_to=Main.models.user_directory_path2)),
                ('totalProducts', models.IntegerField(default=0)),
                ('productVisited', models.TextField()),
                ('wishlisted', models.TextField()),
                ('productBuyed', models.TextField()),
                ('totalBuyed', models.IntegerField(default=0)),
                ('TotalVisited', models.IntegerField(default=0)),
                ('purchased', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('custVoted', models.IntegerField(default=0)),
                ('owner', models.CharField(max_length=70)),
                ('AddressPrimary', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('gender', models.CharField(max_length=50)),
                ('typeOf', models.CharField(max_length=50)),
                ('categories', models.CharField(max_length=150)),
                ('buyed', models.IntegerField(default=0)),
                ('visitedSite', models.IntegerField(default=0)),
                ('AddressPrimary', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('wishlist', models.TextField()),
                ('cart', models.TextField()),
                ('shopVisited', models.TextField()),
                ('productVisited', models.TextField()),
                ('buyedProducts', models.TextField()),
                ('isNew', models.BooleanField(default=True)),
                ('isFirstVisit', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('typeOf', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('actualPrice', models.IntegerField(default=0)),
                ('sellingPrice', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('coupon', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to=Main.models.user_directory_path1)),
                ('image2', models.ImageField(upload_to=Main.models.user_directory_path1)),
                ('image3', models.ImageField(upload_to=Main.models.user_directory_path1)),
                ('stock', models.IntegerField()),
                ('buyed', models.IntegerField()),
                ('wishlist', models.IntegerField()),
                ('views', models.IntegerField()),
                ('searched', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
