# Generated by Django 3.1.4 on 2021-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='AddressPrimary',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='about',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='buyedProducts',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cart',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='postal',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='productVisited',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shopVisited',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='state',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='wishlist',
            field=models.TextField(default='none'),
        ),
    ]
