# Generated by Django 3.1.4 on 2021-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20210124_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cart',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='wishlist',
            field=models.TextField(default=''),
        ),
    ]
