# Generated by Django 3.1.4 on 2021-01-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20210124_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='AddressPrimary',
            new_name='addressPrimary',
        ),
    ]
