# Generated by Django 3.1.4 on 2021-01-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20210125_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
