# Generated by Django 3.1.4 on 2021-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_userinfo_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='contact',
        ),
        migrations.AddField(
            model_name='shop',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
    ]
