# Generated by Django 3.1.4 on 2021-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='searched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.IntegerField(default=0),
        ),
    ]
