# Generated by Django 3.1.4 on 2021-01-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20210126_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
