# Generated by Django 3.1.4 on 2021-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20210126_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='countId',
            field=models.IntegerField(default=0),
        ),
    ]
