# Generated by Django 3.1.4 on 2021-01-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_shop_countid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='countId',
            field=models.IntegerField(default=1),
        ),
    ]
