# Generated by Django 3.1.4 on 2021-01-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_auto_20210127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.TextField(max_length=100),
        ),
    ]
