# Generated by Django 3.1.4 on 2021-01-31 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0018_auto_20210127_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='purchased',
            new_name='totalSale',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='totalBuyed',
        ),
    ]
