# Generated by Django 3.1.4 on 2021-02-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0020_shop_totalstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='searched',
            field=models.IntegerField(default=0),
        ),
    ]
