# Generated by Django 3.1.4 on 2021-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0021_shop_searched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='productBuyed',
        ),
        migrations.AddField(
            model_name='product',
            name='productBuyed',
            field=models.IntegerField(default=0),
        ),
    ]
