# Generated by Django 3.1.4 on 2021-02-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0022_auto_20210202_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productBuyed',
        ),
    ]
