# Generated by Django 3.1.4 on 2021-02-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0023_remove_product_productbuyed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='TotalVisited',
            new_name='totalVisited',
        ),
    ]
